name: CI


on:
  push:
  pull_request:


jobs:
  ci:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build
      run: npx --package mini-cross mc --no-tty _ make

    - name: Upload executable artifacts
      uses: actions/upload-artifact@v3
      with:
        name: minecraft-mod-log-player-health
        path: build/libs/*.jar
        if-no-files-found: error

